/**
 * Self-serve merchant onboarding: register a callback URL for real
 * order/fulfillment event delivery (outbound webhooks — see
 * apps/worker/src/outbox-dispatcher.ts's header for the full write path).
 *
 * DESIGN CHOICE, disclosed: unlike merchant-payment-connection-store.ts
 * (where the merchant brings their OWN Razorpay credentials), the signing
 * secret here is generated by Counter, never supplied by the caller — this
 * is an OUTBOUND webhook (Counter signs, the merchant's system verifies),
 * the same direction and same secret-ownership convention Stripe/GitHub/
 * Shopify's own outbound webhooks use. The merchant only ever supplies the
 * URL; the secret is returned ONCE at registration time (and once again on
 * an explicit rotate), never re-displayed by a later read.
 *
 * SECURITY: signing_secret is a real HMAC key. See migration 0022's header
 * for how it is (and deliberately isn't) protected at rest — same
 * disclosed, no-new-encryption-precedent trade-off as
 * shopify-connection-store.ts's access_token.
 *
 * Writes go straight through parameterized SQL rather than the RBAC-gated
 * PostgresIdentityRepositories, matching every other store in this app —
 * see wallet-user-store.ts's header for the full rationale.
 */
import { randomBytes } from "node:crypto";
import type { Environment } from "@counter/domain";
import type { TransactionalDatabase } from "@counter/data";

export interface WebhookEndpointStatus {
  readonly connected: boolean;
  readonly url?: string;
}

export interface WebhookEndpointRegistration {
  readonly url: string;
  /** Only ever returned once, at registration/rotation time. */
  readonly signingSecret: string;
}

export class WebhookEndpointValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "WebhookEndpointValidationError";
  }
}

export interface MerchantWebhookEndpointStoreLike {
  register(merchantId: string, url: string): Promise<WebhookEndpointRegistration>;
  getStatus(merchantId: string): Promise<WebhookEndpointStatus>;
}

export class MerchantWebhookEndpointStore implements MerchantWebhookEndpointStoreLike {
  constructor(
    private readonly database: TransactionalDatabase,
    private readonly environment: Environment,
  ) {}

  async register(merchantId: string, url: string): Promise<WebhookEndpointRegistration> {
    let parsed: URL;
    try {
      parsed = new URL(url);
    } catch {
      throw new WebhookEndpointValidationError("url must be a valid URL");
    }
    if (parsed.protocol !== "https:") {
      throw new WebhookEndpointValidationError("url must use https://");
    }

    const merchantExists = await this.database.query(
      `SELECT 1 FROM merchant.scopes WHERE environment = $1 AND merchant_id = $2`,
      [this.environment, merchantId],
    );
    if (merchantExists.rows.length === 0) {
      throw new WebhookEndpointValidationError(`No such merchant: ${merchantId}`);
    }

    const signingSecret = `whsec_${randomBytes(24).toString("base64url")}`;
    const now = new Date().toISOString();
    await this.database.query(
      `INSERT INTO merchant.webhook_endpoints
         (environment, merchant_id, url, signing_secret, status, created_at, updated_at)
       VALUES ($1, $2, $3, $4, 'active', $5, $5)
       ON CONFLICT (environment, merchant_id) DO UPDATE
         SET url = EXCLUDED.url,
             signing_secret = EXCLUDED.signing_secret,
             status = 'active',
             updated_at = EXCLUDED.updated_at`,
      [this.environment, merchantId, parsed.toString(), signingSecret, now],
    );

    return { url: parsed.toString(), signingSecret };
  }

  async getStatus(merchantId: string): Promise<WebhookEndpointStatus> {
    const result = await this.database.query<{ url: string }>(
      `SELECT url FROM merchant.webhook_endpoints
        WHERE environment = $1 AND merchant_id = $2 AND status = 'active'`,
      [this.environment, merchantId],
    );
    const row = result.rows[0];
    if (row === undefined) {
      return { connected: false };
    }
    return { connected: true, url: row.url };
  }
}
