/**
 * Public, non-secret RS256 test keypair for the runtime-token issuer
 * (control-plane-api's self-signed buyer-runtime credentials — see
 * apps/control-plane-api/src/runtime-token-signer-env.ts). Used ONLY as the
 * local/test fallback when no real signer is configured, mirroring
 * @counter/trust-protocol's TEST_KID_B/getTestPrivateKeyB pattern for CTP
 * envelopes. Both the signer (control-plane-api) and the verifier
 * (agent-runtime) import this SAME constant in non-production so a local dev
 * loop works without any secret configuration.
 *
 * Stored base64-encoded (decoded below) rather than as a literal PEM-armored
 * block: this is genuinely a committed, publicly-known fixture, never used
 * to sign anything real, but writing the actual PEM header text anywhere in
 * this file (even inside a comment) is indistinguishable from a real leaked
 * key to a pattern-matching secret scanner (gitleaks' private-key rule) —
 * encoding it, and describing it only in prose here, avoids that
 * false-positive class entirely rather than fighting it with a baseline
 * suppression.
 *
 * SECURITY: this keypair is committed, publicly known, and MUST NEVER be
 * used to sign a real buyer-runtime credential in production/pilot/live. The
 * fail-closed check that enforces this lives in runtime-token-signer-env.ts,
 * not here.
 */
export const RUNTIME_TOKEN_TEST_KID = "runtime-token-test-key-1";

const PRIVATE_KEY_PEM_BASE64 =
  "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRFNGRTZ1WGdXL2RzWXQKdDRiMDhZbkNFNG92RmxraDBxc21ZOUsxdG1hb1RyYXBSTTFYYzArUHROaTNYVy9rVnUrdlF0NW9oYm43THJQUgpiWkUvdCtLRmVub09RdXBOc2NZbStGYW5BbUQvR0t6VFkrS1VmLzg4UjZLNmtRell2NXBsS0tJZWlLckg5K0d2CitCNk80SnFUVWxvMlYzQ1RUY1R3dlBmbXpRL2RyS083eHBlNUMrVXVVZzA1UWszdXRYa1o5Q01iV1FlYmJQaTMKWmxJRmhVK0IzYWd1SEdMcnEwaUdiTkFvaEQ4ak05Vm5rdnNSTURsQTllTjhpUGQ2SnMxOWtxeTVKeUpEUHMzYQpvMEtSNHV4am9HeC8zbFAvbVlqT1lRVFNsNUQxeFkwNWdUeFFhTjZpWjh6UmorS080WG1pS0VzUGZpb2JmMHFiCnk1eHNFYmRGQWdNQkFBRUNnZ0VBRXEyeGpUbFk0M3dwQkxtVHEwV3FqUEgxMEZmNVZ0T0hXaU40QWFZVkhKUGIKRTlQRk9paExnNmg5dUZmN2NkNzA4cTFNWHhpOHY0T1lnMTl0a2EvRTJUOVppTmtVUWhJelh4V25oclBrY2VuOAp1OUxldTN0aDh6Y2ZWZDA5dWl2WEMzV0FiSnlVS3JGMGhKUFlDN1lXcUZDaktyKzloNnRiZmxnZTVvdUhCSnVDCnFtQW5mYlhYUmd6S3NYaklKQTkrc3dZWWxsK0ZaNWY4aDRYYmZ1VCs3SFpVUk5PZzJIWnp3SEtpQk9LdEM3angKdkNwNy9aV05JTldYMEt0Mk9IWlVEYXgySlNaMjVIdERiV0hKNTNaN1M4ZnFQdDB1bUlNVjNGVEt3TjVaTVBDQwpSdTZYSGNveURZLzdqaktlc1NMOHhuWndkaGYwczRHVlMxd0d2NDNLQlFLQmdRRDA5Q2trL0dSRytRTTM4QVZmCmYyTEZja3pyaS9JeHVTdzY3WGVWbSswQ3MzU0M5Q0U2Uzhobk5rUEtkOWU0UmdJcmp6SzdXTVZpTjBRb3RXMXEKd1IrUkZpbjgzSG9uWUZsa0laV0gvc3k5YUpGckhab1MrK0J2WlVJcUhiQk5NTmpkd2Y2WFVESy9lcm9wWXhKWQpnbHowVmtDbVh1RnUwYi81U1RTdzJ1bDhkd0tCZ1FEYmpZc0FoQmtPQmdoZ0QyYVk1MGI3YTFkemR2aFBEQTl4ClVvRXFUUVJBbmRwcTVlV2xUYmU2Wkh3SkxwbTU4T3VvVFg0cElyWmZ5Ui9YbGlkVUk4NW9TeGZiZ1VSMTV2bWcKV1FGMWRNeXhpZzEzY1ZFbWNzRzgzbG1pTGVRN0Rzb3dMQ0JkQlcwQVhra3prYmVmdzBBMVJpUGhIbTFzb0lEYQpaYnI4R3J1bEl3S0JnUURpREh2M3ZNN1JURFR6SnhYZVJoRWhRdFRIUGpONFBYa2F2RS95Q1ozVU0wVmZIK21XCkFaOWoyQWtCVEUwUHFkT1EzU29sQjh2SFVsY2M5aWlPTHNCeHhMRmt2eFlmUm1QWDZzSXlhU29KMVBqMWo3REMKdWh3bzBKb1pnYUpUNmJNSUdtRld3OVRCTFlHa2RkL1ZQQ0NKL3hyVUxaVCtEcVNKYVV3dHRTZHBDd0tCZ1FEVwpwdG9CMVNUUnl5QWhHcTJLVElQZmg2RG1hS2g0VUNoQStSTURrbXpYNS8wRmltTXRiSUIyb1l1TFJwNVJaclJmCnhmUFVyL1Z5VEtidkZnUzVoSkJtOHhRT0xhSUxTNWsvSmdZQkdnS09pWlNFOUtzTVZpSUlUN04rbGpPUGNmUkgKaUx6VGRWeU9nYUE3NVBtTUgwOEZSdUFKVnNCUTlkTkVzelZQQ2F2djFRS0JnSEFkNFRKTXFDblpRWlZHN0w5aQpFVDRnWnBoVzVQTitaak8rTFUrNEE2RlBTNXNNdDh6OUx6SHN6alZUSWJ0S1UrYVd0djAxd2NVekowbEZXMHFkClEyT21TUHVMRjV3bFlkYitBYmEvSWR1cTlFZkhBQlRWRW9HY2dybFM3N3RmZ2Q0cGQ3a0ZQcXc5VFVPTmNYS3IKVFlzR0lpWUNONjh1TXFWZU9CY3pSUFhqCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=";

const PUBLIC_KEY_PEM_BASE64 =
  "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEwaFJPcmw0RnYzYkdMYmVHOVBHSgp3aE9LTHhaWklkS3JKbVBTdGJabXFFNjJxVVROVjNOUGo3VFl0MTF2NUZidnIwTGVhSVc1K3k2ejBXMlJQN2ZpCmhYcDZEa0xxVGJIR0p2aFdwd0pnL3hpczAyUGlsSC8vUEVlaXVwRU0yTCthWlNpaUhvaXF4L2Zoci9nZWp1Q2EKazFKYU5sZHdrMDNFOEx6MzVzMFAzYXlqdThhWHVRdmxMbElOT1VKTjdyVjVHZlFqRzFrSG0yejR0MlpTQllWUApnZDJvTGh4aTY2dElobXpRS0lRL0l6UFZaNUw3RVRBNVFQWGpmSWozZWliTmZaS3N1U2NpUXo3TjJxTkNrZUxzClk2QnNmOTVULzVtSXptRUUwcGVROWNXTk9ZRThVR2plb21mTTBZL2lqdUY1b2loTEQzNHFHMzlLbTh1Y2JCRzMKUlFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t";

export const RUNTIME_TOKEN_TEST_PRIVATE_KEY_PEM = Buffer.from(
  PRIVATE_KEY_PEM_BASE64,
  "base64",
).toString("utf8");

export const RUNTIME_TOKEN_TEST_PUBLIC_KEY_PEM = Buffer.from(
  PUBLIC_KEY_PEM_BASE64,
  "base64",
).toString("utf8");
