"use client";

import { useState } from "react";
import { mfa } from "@auth0/nextjs-auth0/client";
import { Button, Card, CardContent, CardHeader, CardTitle, Input, Badge } from "@counter/ui";
import { ShieldCheck, KeyRound, CheckCircle2 } from "lucide-react";
import { createCounterId, type CounterId } from "@counter/domain";
import {
  InMemorySigner,
  signEnvelope,
  derivePublicKey,
  computeSha256Digest,
} from "@counter/trust-protocol";
import { buildMandateEnvelope } from "@counter/wallet-application/mandate-service";
import type { BuyerPolicyConstraints } from "@counter/wallet-domain";

const API_AUDIENCE = "https://api.counter.dev";
// Deliberately NOT passing an explicit `scope` to challengeWithPopup: the
// SDK's own source (client/mfa/index.js) documents that omitting it makes
// the popup inherit the app's global scope config (which already includes
// wallet:read wallet:write, via lib/auth0.ts) AND keeps getAccessToken()'s
// post-popup cache lookup using the SAME default key — passing an explicit
// scope here once caused a real AccessTokenError from a cache-key mismatch
// between what the popup stored and what the lookup afterward searched for.

type Step =
  | { status: "idle" }
  | { status: "step-up"; label: string }
  | { status: "generating-key" }
  | { status: "registering-key" }
  | { status: "signing" }
  | { status: "submitting" }
  | { status: "done"; mandateId: string; agentId: string }
  | { status: "error"; message: string };

function randomBytes(length: number): Uint8Array {
  return crypto.getRandomValues(new Uint8Array(length));
}

/** Derives the wallet owner's own actor id — same convention every existing
 * CLI script in this repo uses (scripts/issue-and-bind-wallet-mandate.mjs):
 * the wallet id's own entropy segment, reused under the "actor" kind. Not
 * independently verified server-side (see mandate-binding-store.ts), so any
 * consistent, deterministic derivation is fine — this just avoids a second
 * round trip to look one up. */
function derivePrincipalId(walletId: string): string {
  return walletId.replace(/^ctr_wallet_/, "ctr_actor_");
}

async function postJson<T>(
  url: string,
  body: unknown,
): Promise<{ ok: true; value: T } | { ok: false; message: string }> {
  const response = await fetch(url, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(body),
  });
  const parsed = (await response.json().catch(() => undefined)) as
    | (T & { error?: { message?: string } })
    | undefined;
  if (!response.ok) {
    return { ok: false, message: parsed?.error?.message ?? `Request failed (${response.status})` };
  }
  return { ok: true, value: parsed as T };
}

export function ConnectPanel({ walletId }: { walletId: string }) {
  const [step, setStep] = useState<Step>({ status: "idle" });
  const [agentId, setAgentId] = useState("");
  const [ceilingRupees, setCeilingRupees] = useState("2000");
  const [merchantAllowlist, setMerchantAllowlist] = useState("");
  const [validDays, setValidDays] = useState("365");

  const busy = step.status !== "idle" && step.status !== "error" && step.status !== "done";

  async function handleAuthorize() {
    const ceilingMinor = Math.round(Number(ceilingRupees) * 100);
    if (!Number.isFinite(ceilingMinor) || ceilingMinor <= 0) {
      setStep({ status: "error", message: "Enter a valid spend ceiling greater than zero." });
      return;
    }
    const days = Number.parseInt(validDays, 10);
    if (!Number.isFinite(days) || days <= 0) {
      setStep({ status: "error", message: "Enter a valid number of days." });
      return;
    }
    const allowedMerchantIds = merchantAllowlist
      .split(",")
      .map((m) => m.trim())
      .filter((m) => m.length > 0);

    try {
      // 1. Step-up: this whole flow is gated server-side by
      // payment.mandate.manage / identity.agent_key.manage, which require
      // step-up assurance — trigger it once, up front, covering every
      // request below.
      setStep({ status: "step-up", label: "Confirming it's really you…" });
      try {
        await mfa.challengeWithPopup({ audience: API_AUDIENCE });
      } catch (stepUpError) {
        console.error("[connect] step-up failed:", stepUpError);
        const name = stepUpError instanceof Error ? stepUpError.name : "UnknownError";
        const detail = stepUpError instanceof Error ? stepUpError.message : String(stepUpError);
        setStep({
          status: "error",
          message: `Verification step failed (${name}): ${detail}`,
        });
        return;
      }

      // 2. Generate a disposable "consent" keypair — its ONLY job is to
      // sign this mandate, proving a human (not just a session) approved
      // these exact guardrails. It is NOT your AI agent's own operating
      // key (that one lives on your own machine, generated by
      // register-agent-self-serve.mjs, and never touches this browser).
      setStep({ status: "generating-key" });
      const privateKey = randomBytes(32);
      const publicKeyBase64Url = derivePublicKey(privateKey);
      const keyIdResult = createCounterId("key", randomBytes(16));
      if (!keyIdResult.ok) {
        setStep({ status: "error", message: "Could not generate a key id. Please try again." });
        return;
      }
      const kid = keyIdResult.value;

      // 3. Register the consent key's public half (real, durable — see
      // apps/control-plane-api/src/wallet-user-routes.ts). Needs a
      // single-use setup token, minted by the SAME step-up-elevated
      // session.
      setStep({ status: "registering-key" });
      const setupTokenResult = await postJson<{ setupToken: string }>("/api/setup-token", {});
      if (!setupTokenResult.ok) {
        setStep({ status: "error", message: setupTokenResult.message });
        return;
      }
      const registerResult = await postJson<{ agentId: string; keyId: string }>("/api/agent-keys", {
        setupToken: setupTokenResult.value.setupToken,
        keyId: kid,
        publicKeyBase64Url,
      });
      if (!registerResult.ok) {
        setStep({ status: "error", message: registerResult.message });
        return;
      }
      // Registering the consent key above also mints a real, active,
      // wallet-owned agent (control-plane-api's registerAgentKey). When the
      // buyer hasn't already run register-agent-self-serve.mjs on their own
      // machine, that agent IS the one to authorize — otherwise this page
      // couldn't be used at all without first running a CLI script, which is
      // exactly the engineer-in-the-loop dependency it exists to remove.
      // Either way the server independently checks payload.agent_id is a
      // real, active agent owned by this wallet (mandate-binding-store.ts's
      // agentOwnershipCheck), so a typed-in value is never taken on trust.
      const effectiveAgentId =
        agentId.trim().length > 0 ? agentId.trim() : registerResult.value.agentId;

      // 4. Build + sign the mandate envelope. Signing happens ENTIRELY in
      // this browser tab with the consent key generated in step 2 — the
      // private key is never sent anywhere and is discarded when this page
      // is left.
      setStep({ status: "signing" });
      const constraints: BuyerPolicyConstraints = {
        merchantAllowlist: { allowedMerchantIds, allowedDomains: [] },
        geography: { allowedMerchantCountries: [], allowedDeliveryCountries: [] },
        category: { allowedCategories: [] },
        currency: { allowedCurrencies: ["INR"] },
        amountLimits: { perTransactionMaxPaise: BigInt(ceilingMinor) },
        countLimits: {},
        operations: { allowedOperations: ["purchase"] },
        timeConstraints: {},
        approvalThreshold: { thresholdPaise: BigInt(ceilingMinor) },
        paymentReferences: { allowedReferenceIds: [] },
      };
      const now = new Date();
      const validUntil = new Date(now.getTime() + days * 24 * 60 * 60 * 1000);
      const paymentReferenceId = `ctr_payment-reference_self-consent-${crypto.randomUUID().replace(/-/g, "")}`;
      // A real digest of the exact guardrails being approved — computed
      // in-browser, at consent time, over the same values the buyer sees
      // on screen. See mandate-service.ts's header for why this doesn't
      // need to be a full second signed envelope: the binding route
      // doesn't independently re-verify this digest against anything
      // (unlike the mandate signature itself, which it does verify).
      const consentAttestationDigest = computeSha256Digest(
        new TextEncoder().encode(
          JSON.stringify({
            walletId,
            agentId: effectiveAgentId,
            ceilingMinor,
            allowedMerchantIds,
            validUntil,
          }),
        ),
      );

      const envelopeResult = buildMandateEnvelope({
        walletId: walletId as CounterId<"wallet">,
        principalId: derivePrincipalId(walletId) as CounterId<"actor">,
        agentId: effectiveAgentId as CounterId<"agent">,
        kid,
        constraints,
        paymentReferenceId,
        validFrom: now.toISOString(),
        validUntil: validUntil.toISOString(),
        consentAttestationDigest,
        policyVersionId: "wallet-console-v1",
        correlationId: crypto.randomUUID(),
      });
      if (!envelopeResult.ok) {
        setStep({ status: "error", message: envelopeResult.error.reason });
        return;
      }

      const signer = new InMemorySigner(kid, privateKey);
      const signedResult = await signEnvelope(envelopeResult.value.envelope, signer);
      if (!signedResult.ok) {
        setStep({ status: "error", message: signedResult.error.message });
        return;
      }

      // 5. Submit the signed envelope. Server independently re-verifies
      // the signature, that the consent key is really registered, and
      // that agentId is a real, active agent owned by this wallet before
      // persisting anything — see mandate-binding-store.ts.
      setStep({ status: "submitting" });
      const submitResult = await postJson<{ mandateId: string }>("/api/mandates", {
        envelope: signedResult.value,
      });
      if (!submitResult.ok) {
        setStep({ status: "error", message: submitResult.message });
        return;
      }

      setStep({
        status: "done",
        mandateId: submitResult.value.mandateId,
        agentId: effectiveAgentId,
      });
    } catch (unexpectedError) {
      console.error("[connect] unexpected failure:", unexpectedError);
      const name = unexpectedError instanceof Error ? unexpectedError.name : "UnknownError";
      const detail =
        unexpectedError instanceof Error ? unexpectedError.message : String(unexpectedError);
      setStep({
        status: "error",
        message: `Unexpected error (${name}): ${detail}`,
      });
    }
  }

  if (step.status === "done") {
    return (
      <Card className="border-green-500/30">
        <CardContent className="p-6">
          <div className="flex items-center gap-3">
            <CheckCircle2 className="h-6 w-6 text-green-500" />
            <div>
              <p className="font-semibold text-[var(--foreground)]">Authorized</p>
              <p className="text-sm text-[var(--foreground-muted)]">
                Your AI agent may now spend up to ₹{ceilingRupees} per purchase within these
                guardrails.
              </p>
            </div>
          </div>
          <div className="mt-4 grid grid-cols-2 gap-3 text-sm">
            <div>
              <p className="text-[var(--foreground-muted)]">Mandate ID</p>
              <p className="font-mono text-xs text-[var(--foreground)]">{step.mandateId}</p>
            </div>
            <div>
              <p className="text-[var(--foreground-muted)]">Agent ID</p>
              <p className="font-mono text-xs text-[var(--foreground)]">{step.agentId}</p>
            </div>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-base">
          <ShieldCheck className="h-4 w-4 text-[var(--brand-orange)]" />
          Authorize your agent
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div>
          <label className="mb-1 block text-sm font-medium text-[var(--foreground)]">
            Agent ID <span className="font-normal text-[var(--foreground-muted)]">(optional)</span>
          </label>
          <Input
            value={agentId}
            onChange={(e) => {
              setAgentId(e.target.value);
            }}
            placeholder="ctr_agent_..."
            disabled={busy}
          />
          <p className="mt-1 text-xs text-[var(--foreground-muted)]">
            Printed by <code>register-agent-self-serve.mjs</code> if you already connected your AI
            tool. Leave blank to authorize the agent this page registers for you.
          </p>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="mb-1 block text-sm font-medium text-[var(--foreground)]">
              Max per purchase (₹)
            </label>
            <Input
              type="number"
              min="1"
              value={ceilingRupees}
              onChange={(e) => {
                setCeilingRupees(e.target.value);
              }}
              disabled={busy}
            />
          </div>
          <div>
            <label className="mb-1 block text-sm font-medium text-[var(--foreground)]">
              Valid for (days)
            </label>
            <Input
              type="number"
              min="1"
              value={validDays}
              onChange={(e) => {
                setValidDays(e.target.value);
              }}
              disabled={busy}
            />
          </div>
        </div>
        <div>
          <label className="mb-1 block text-sm font-medium text-[var(--foreground)]">
            Merchant allowlist (comma-separated Counter merchant IDs — leave blank for none yet)
          </label>
          <Input
            value={merchantAllowlist}
            onChange={(e) => {
              setMerchantAllowlist(e.target.value);
            }}
            placeholder="ctr_merchant_..., ctr_merchant_..."
            disabled={busy}
          />
        </div>

        <Button
          onClick={() => {
            void handleAuthorize();
          }}
          disabled={busy}
          className="w-full"
        >
          <KeyRound className="mr-2 h-4 w-4" />
          {step.status === "step-up"
            ? step.label
            : step.status === "generating-key"
              ? "Generating a signing key…"
              : step.status === "registering-key"
                ? "Registering…"
                : step.status === "signing"
                  ? "Signing…"
                  : step.status === "submitting"
                    ? "Submitting…"
                    : "Authorize"}
        </Button>
        {step.status === "error" && <p className="text-sm text-red-500">{step.message}</p>}
        <Badge variant="secondary" className="text-[10px]">
          Your private key never leaves this browser tab
        </Badge>
      </CardContent>
    </Card>
  );
}
