/**
 * FileSecureKeyStore tests.
 *
 * The generic SecureKeyStore conformance suite (secure-key-store.test.ts)
 * assumes a credential fixed at construction time, which doesn't fit this
 * implementation (the credential is supplied to unlockStore(), and the first
 * ever unlock against a fresh file adopts whatever credential it's given —
 * there's nothing on disk yet to compare against). So this file tests the
 * behavior that's actually new here: real persistence across store instances
 * (i.e. across process restarts), and wrong-passphrase rejection once a file
 * genuinely exists.
 */

import { describe, it, expect, afterEach } from "vitest";
import { mkdtempSync, rmSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import * as ed from "@noble/ed25519";
import { FileSecureKeyStore } from "./file-key-store.js";

let tempDir: string | undefined;

function freshKeyStorePath(): string {
  tempDir = mkdtempSync(join(tmpdir(), "counter-wallet-key-store-test-"));
  return join(tempDir, "wallet-keys.enc.json");
}

afterEach(() => {
  if (tempDir !== undefined) {
    rmSync(tempDir, { recursive: true, force: true });
    tempDir = undefined;
  }
});

describe("FileSecureKeyStore", () => {
  it("generates a valid Ed25519 key and signs data that verifies against the public key", async () => {
    const store = new FileSecureKeyStore(freshKeyStorePath());
    store.unlockStore("a-real-passphrase");

    const { keyId, publicKey } = await store.generateKey("agent-signing");
    expect(publicKey.byteLength).toBe(32);

    const message = new TextEncoder().encode("hello");
    const signature = await store.sign(keyId, message);
    expect(await ed.verifyAsync(signature, message, publicKey)).toBe(true);
  });

  it("writes the key file to disk", async () => {
    const path = freshKeyStorePath();
    expect(existsSync(path)).toBe(false);
    const store = new FileSecureKeyStore(path);
    store.unlockStore("a-real-passphrase");
    await store.generateKey("agent-signing");
    expect(existsSync(path)).toBe(true);
  });

  it("round-trips: a key generated by one store instance is usable by a fresh instance pointed at the same file", async () => {
    const path = freshKeyStorePath();

    const first = new FileSecureKeyStore(path);
    first.unlockStore("a-real-passphrase");
    const { keyId, publicKey } = await first.generateKey("agent-signing");

    const second = new FileSecureKeyStore(path);
    second.unlockStore("a-real-passphrase");

    const message = new TextEncoder().encode("proof of persistence");
    const signature = await second.sign(keyId, message);
    expect(await ed.verifyAsync(signature, message, publicKey)).toBe(true);

    const descriptor = await second.getPublicDescriptor(keyId);
    expect(descriptor?.status).toBe("active");
  });

  it("rejects the wrong passphrase against an existing file", async () => {
    const path = freshKeyStorePath();
    const first = new FileSecureKeyStore(path);
    first.unlockStore("correct-passphrase");
    await first.generateKey("agent-signing");

    const second = new FileSecureKeyStore(path);
    expect(() => second.unlockStore("wrong-passphrase")).toThrow("Invalid credential");
  });

  it("rejects sign() while locked", async () => {
    const store = new FileSecureKeyStore(freshKeyStorePath());
    store.unlockStore("a-real-passphrase");
    const { keyId } = await store.generateKey("agent-signing");
    store.lockStore();
    await expect(store.sign(keyId, new Uint8Array([1, 2, 3]))).rejects.toThrow("locked");
  });

  it("rejects sign() with a revoked key", async () => {
    const store = new FileSecureKeyStore(freshKeyStorePath());
    store.unlockStore("a-real-passphrase");
    const { keyId } = await store.generateKey("agent-signing");
    await store.revokeKey(keyId);
    await expect(store.sign(keyId, new Uint8Array([1, 2, 3]))).rejects.toThrow("revoked");
  });

  it("revocation persists across store instances", async () => {
    const path = freshKeyStorePath();
    const first = new FileSecureKeyStore(path);
    first.unlockStore("a-real-passphrase");
    const { keyId } = await first.generateKey("agent-signing");
    await first.revokeKey(keyId);

    const second = new FileSecureKeyStore(path);
    second.unlockStore("a-real-passphrase");
    const descriptor = await second.getPublicDescriptor(keyId);
    expect(descriptor?.status).toBe("revoked");
  });

  it("never includes private key material in toString() or toJSON()", async () => {
    const store = new FileSecureKeyStore(freshKeyStorePath());
    store.unlockStore("a-real-passphrase");
    await store.generateKey("agent-signing");

    expect(store.toString()).not.toContain("privateKey");
    const json = JSON.stringify(store);
    expect(json).not.toContain("privateKey");
  });
});
